### ISSUE TITLE
Adding SWD pins

### ISSUE THREAD

**Issue by CamDavidsonPilon** [pinout-xyz/pico.pinout.xyz#7]
:wave: A nice addition would be labelling the SWD pins on the bottom

**Comment by Gadgetoid** [comment]
Ooh, that should be pretty doable too!

**Comment by Gadgetoid** [comment]
Added to "Advanced" view on https://pico.pinout.xyz/, not quite sure how I'll handle this on Pico W yet, but in both cases the debug pins are actually labelled in the SVG on "Rear View" anyway.

**Comment by CamDavidsonPilon** [comment]
Thanks!
