### ISSUE TITLE
Mislabelled pin function

### ISSUE THREAD

**Issue by lurch** [pinout-xyz/pico.pinout.xyz#8]
When you click on the "Advanced" box on https://pico.pinout.xyz/ it shows GP18 as "UART1 RTS", but page 18 of https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf says GP18 is "UART0 CTS".

**Comment by ali1234** [comment]
GP19 UART function looks wrong as well. It is where UART0 RTS should go.

**Comment by lurch** [comment]
Huh, I've just noticed that the mouse-hover text for those pins actually seems correct :laughing:

**Comment by Gadgetoid** [comment]
What's the deal with the tooltip on the pin above it though, aaaaaagh!

Maybe I should be generating this HTML from a dataset.

**Comment by lurch** [comment]
Looks like the hover-text for GP27's UART mode is wrong as well? The page says "UART1 RTS" (which agrees with https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf ) but the hover-text says "UART 0: Clear to send".

**Comment by Gadgetoid** [comment]
Finally fixed this last little bug. Hopefully that's all of them!
